distributable:
  url: https://github.com/pvolok/mprocs/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

provides:
  - bin/mprocs

versions:
  github: pvolok/mprocs/tags

build:
  dependencies:
    rust-lang.org: '>=1.56'
    rust-lang.org/cargo: '*'
  script:
    cargo install --locked --path ./src --root {{prefix}}

test:
  script: |
    mprocs --version
